### ISSUE TITLE
Cryptonator service unavailable V1.1.1

### ISSUE THREAD

**Issue by pinthenet** [BigNocciolino/CryptoTracker#15] opened 2022-01-25 10:30 UTC
I've not received any updates since around 18:30 CET on 24th Jan. Found the following in the HA log:
`Request returned a bad error code 503
11:26:31 – (ERROR) cryptostate (custom integration) - message first occurred at 24 January 2022, 20:31:57 and shows up 1790 times
503 Server Error: Service Temporarily Unavailable for url: https://api.cryptonator.com/api/ticker/eth-eur
11:26:31 – (ERROR) cryptostate (custom integration) - message first occurred at 24 January 2022, 20:31:57 and shows up 1790 times
`
I can access the URL from a browser without error. I have restarted HA (twice).
Any one else?

**Comment by Revival67** [comment] 2022-01-25 10:35
Same problem here, also since yesterday no data.

**Comment by BigNocciolino** [comment] 2022-01-25 10:47
Hi, thanks for reporting, today I found this issue, but now I can not investigate. This afternoon I will try.

**Comment by pinthenet** [comment] 2022-01-25 10:56
Good that you found it so quickly Alfonso.

No rush at the moment, everything’s going down anyway :-P

**Comment by t34wrj** [comment] 2022-01-25 12:32
Same here.

**Comment by ruigaspar** [comment] 2022-01-25 13:50
The problem is with the cryptonator API.
Now they added a browser checking before access to the website, but unfortunately also added it to the API. 
I think they will fix this, I hope...

<img width="1680" alt="Screen Shot 2022-01-25 at 13 44 09" src="https://user-images.githubusercontent.com/1328737/150988605-0692d00c-6da4-48a6-a314-24b6578030ce.png">
<img width="1680" alt="Screen Shot 2022-01-25 at 13 44 25" src="https://user-images.githubusercontent.com/1328737/150988616-0a341ba7-a358-4225-8570-ca8c921fb9a1.png">

**Comment by BigNocciolino** [comment] 2022-01-25 14:00
Yes, they seem to have restricted the API access to the web page only, in fact the API is unreachable with  `curl`, `wget` and `postman` 

I hope they will fix this...

### This is the postman output:
![2022-01-25_14-54](https://user-images.githubusercontent.com/59704096/150989803-19cd75ac-e87f-4fc8-a664-7d07c6004d08.png)

**Comment by ruigaspar** [comment] 2022-01-25 14:06
> Yes, they seem to have restricted the API access to the web page only, in fact the API is unreachable with `curl`, `wget` and `postman`
> 
> I hope they will fix this...
> 
> ### This is the postman output:
> ![2022-01-25_14-54](https://user-images.githubusercontent.com/59704096/150989803-19cd75ac-e87f-4fc8-a664-7d07c6004d08.png)

Exactly,
We need to wait or explore another data source API....

**Comment by ruigaspar** [comment] 2022-01-25 20:36
API fixed. @BigNocciolino you can close the issue...

**Comment by t34wrj** [comment] 2022-01-25 20:37
Back for me too!

**Comment by pinthenet** [comment] 2022-01-26 07:05
+1On 25 Jan 2022 21:37, t34wrj ***@***.***> wrote:
Back for me too!

**Comment by kevincaradant** [comment] 2022-01-28 22:38
Hi @BigNocciolino 

Indeed it working again since 3 days. However, I got always so many failed on logs

13000 failed occurrences :/. Is it possible to contact less often the api?

Thank you

Regards 
![Screenshot_20220128-233613_Home Assistant](https://user-images.githubusercontent.com/6093175/151631057-cb56b1ad-dc1d-4946-9461-c65f278a418e.jpg)

Some crypto doesn't load also :(

![image](https://user-images.githubusercontent.com/6093175/151661396-9dc6df59-6510-40ae-b858-5be22b190048.png)


NB: @BigNocciolino ,  If needed I open a new issu but I thought it was maybe the same ;)

**Comment by BigNocciolino** [comment] 2022-01-29 17:04
Hi, thanks for reporting, I have increased the scan interval of the component. If that doesn't solve the problem, please open a new issue

**Comment by kevincaradant** [comment] 2022-01-29 17:52
OK thank you I will update when it will be release on hacs and I will tell you

**Comment by pinthenet** [comment] 2022-02-05 07:35
I'm seeing 503 again since yesterday afternoon.

**Comment by BigNocciolino** [comment] 2022-02-05 12:32
Hi, really weird things have been going on since about yesterday afternoon, it seems that their sites have gone completely down, even the website.

**This happens when I try to reach their site:**
![sium](https://user-images.githubusercontent.com/59704096/152642094-743721c8-bd2e-4dbf-92cf-9c1cf00b7708.png)

The API remains online, but can only be accessed from a browser, as these are the outputs of:

- ### Browser:
![2022-02-05_13-19](https://user-images.githubusercontent.com/59704096/152642127-a2bccb0c-bab7-4895-a667-0f486e861975.png)

- ### Wget:
```bash
[alfonso@Fisso ~]$ wget https://api.cryptonator.com/api/ticker/btc-usd
--2022-02-05 13:28:28--  https://api.cryptonator.com/api/ticker/btc-usd
SSL_INIT
Caricato certificato CA "/etc/ssl/certs/ca-certificates.crt"

Risoluzione di api.cryptonator.com (api.cryptonator.com)... 104.22.62.82, 104.22.63.82, 172.67.10.138, ...
Connessione a api.cryptonator.com (api.cryptonator.com)|104.22.62.82|:443... connesso.
Richiesta HTTP inviata, in attesa di risposta... 503 Service Temporarily Unavailable
2022-02-05 13:28:28 ERRORE 503: Service Temporarily Unavailable.
```

EDIT: I hope they solve it as soon as possible, otherwise I could also consider using a different api, which does not require authentication / account creation.

**Comment by pinthenet** [comment] 2022-02-05 13:46
In the last hour I think I’ve started to get responses again but always the same value (right side of graph). There was also a strange spike (actually 2) around yesterday lunchtime

Correction: I was too quick, I think it's working again

**Comment by BigNocciolino** [comment] 2022-02-05 15:58
Now the API seems to be working, but there is a waiting time of about one minute:

![2022-02-05_16-53](https://user-images.githubusercontent.com/59704096/152648890-51d58a23-ceb2-479b-bf20-44cbeb8e97e6.png)

This causes other problems, and therefore a delay for each sensor of about 10 seconds before failing at startup, also causing the problem of @kevincaradant in #19 (
This is a solvable problem, I'll commit for the fix later)

**Comment by pinthenet** [comment] 2022-02-08 17:32
Any news?On 5 Feb 2022 16:58, Alfonso Sorrentino ***@***.***> wrote:
Now the API seems to be working, but there is a waiting time of about one minute:

This causes other problems, and therefore a delay for each sensor of about 10 seconds before failing at startup, also causing the problem of @kevincaradant in #19 (
This is a solvable problem, I'll commit for the fix later)

**Comment by BigNocciolino** [comment] 2022-02-08 23:16
Hi, since this big problems with the Cryptonator API, i'm moving this project to a new API, provided by @fawazahmed0 ([currency-api](https://github.com/fawazahmed0/currency-api)).

Development is taking place in the new branch [new_api](https://github.com/BigNocciolino/CryptoTracker/tree/new_api), also check the #20 PR

**Comment by pinthenet** [comment] 2022-02-10 12:40
Thanks for the update Alfonso, good luck

**Comment by BigNocciolino** [comment] 2022-02-16 18:05
Hi I'm closing all the old issues, if there are problems with the new version, please open a new issue

**Closed as completed by BigNocciolino** 2022-02-16 18:05 UTC
